import initModal from "./modules/modal.js";
import initTabNav from "./modules/tab-nav.js";
import initTooltip from "./modules/tooltip.js";
import initAcoordion from "./modules/accordion.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initScrollSuave from "./modules/scroll-suave.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFucionamento from "./modules/funcionamento.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initScrollAnimation from "./modules/scroll-animacao.js";

initModal();
initTabNav();
initTooltip();
initAcoordion();
initMenuMobile();
initScrollSuave();
initFetchAnimais();
initFucionamento();
initDropdownMenu();
initScrollAnimation();
